name: Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        cp LICENSE LICENSE-linux-x64.zip
        cp LICENSE LICENSE-linux-arm64.zip
        cp LICENSE LICENSE-linux-riscv64.zip
        cp README.md README-linux-x64.zip
      shell: bash
    - uses: actions/cache/save@v4
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}
        enableCrossOsArchive: true
    - uses: actions/cache/save@v4
      with:
        path: LICENSE-linux-arm64.zip
        key: LICENSE-linux-arm64.zip-${{ github.sha }}
    - uses: actions/cache/save@v4
      with:
        path: LICENSE-linux-riscv64.zip
        key: LICENSE-linux-riscv64.zip-${{ github.sha }}
        enableCrossOsArchive: true
    - uses: actions/cache/save@v4
      with:
        path: README-linux-x64.zip
        key: README-linux-x64.zip-${{ github.sha }}
        enableCrossOsArchive: true

  macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - run: |
        cp LICENSE LICENSE-macos-x64.zip
        cp LICENSE LICENSE-macos-arm64.zip
        cp README.md README-macos-x64.zip
      shell: bash
    - uses: actions/cache/save@v4
      with:
        path: LICENSE-macos-x64.zip
        key: LICENSE-macos-x64.zip-${{ github.sha }}
        enableCrossOsArchive: true
    - uses: actions/cache/save@v4
      with:
        path: LICENSE-macos-arm64.zip
        key: LICENSE-macos-arm64.zip-${{ github.sha }}
        enableCrossOsArchive: true
    - uses: actions/cache/save@v4
      with:
        path: README-macos-x64.zip
        key: README-macos-x64.zip-${{ github.sha }}
        enableCrossOsArchive: true

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: Copy-Item "LICENSE" -Destination "LICENSE-windows-x64.zip"
      shell: powershell
    - uses: actions/cache/save@v4
      with:
        path: LICENSE-windows-x64.zip
        key: LICENSE-windows-x64.zip-${{ github.sha }}
        enableCrossOsArchive: true

  test-and-release:
    needs:
      - linux
      - macos
      - windows
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        discard-shelf: false
    - run: |
        if [ ! -f "LICENSE-linux-x64.zip" ]; then
          echo "LICENSE-linux-x64.zip does not exist"
          exit 1
        fi
        if [ ! -f "LICENSE-linux-arm64.zip" ]; then
          echo "LICENSE-linux-arm64.zip does not exist"
          exit 1
        fi
        if [ ! -f "LICENSE-linux-riscv64.zip" ]; then
          echo "LICENSE-linux-riscv64.zip does not exist"
          exit 1
        fi
        if [ ! -f "LICENSE-macos-x64.zip" ]; then
          echo "LICENSE-macos-x64.zip does not exist"
          exit 1
        fi
        if [ ! -f "LICENSE-macos-arm64.zip" ]; then
          echo "LICENSE-macos-arm64.zip does not exist"
          exit 1
        fi
        if [ ! -f "LICENSE-windows-x64.zip" ]; then
          echo "LICENSE-windows-x64.zip does not exist"
          exit 1
        fi
      shell: bash
    - uses: ./
      with:
        name: README
        include-linux-arm64: false
        include-linux-riscv64: false
        include-macos-arm64: false
        include-windows: false
        discard-shelf: false
    - run: |
        if [ ! -f "README-linux-x64.zip" ]; then
          echo "README-linux-x64.zip does not exist"
          exit 1
        fi
        if [ ! -f "README-macos-x64.zip" ]; then
          echo "README-macos-x64.zip does not exist"
          exit 1
        fi
        if [ -f "README-windows-x64.zip" ]; then
          echo "README-windows-x64.zip does not exist"
          exit 1
        fi
      shell: bash
    - uses: ./
    - run: rm LICENSE-linux-x64.zip LICENSE-linux-arm64.zip LICENSE-linux-riscv64.zip LICENSE-macos-x64.zip LICENSE-macos-arm64.zip LICENSE-windows-x64.zip README-linux-x64.zip README-macos-x64.zip
      shell: bash
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}
        fail-on-cache-miss: false
        enableCrossOsArchive: true
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-linux-arm64.zip
        key: LICENSE-linux-arm64.zip-${{ github.sha }}
        fail-on-cache-miss: false
        enableCrossOsArchive: true
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-linux-riscv64.zip
        key: LICENSE-linux-riscv64.zip-${{ github.sha }}
        fail-on-cache-miss: false
        enableCrossOsArchive: true
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-macos-x64.zip
        key: LICENSE-macos-x64.zip-${{ github.sha }}
        fail-on-cache-miss: false
        enableCrossOsArchive: true
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-macos-arm64.zip
        key: LICENSE-macos-arm64.zip-${{ github.sha }}
        fail-on-cache-miss: false
        enableCrossOsArchive: true
    - uses: actions/cache/restore@v4
      with:
        path: LICENSE-windows-x64.zip
        key: LICENSE-windows-x64.zip-${{ github.sha }}
        fail-on-cache-miss: false
        enableCrossOsArchive: true
    - run: |
        if [ -f "LICENSE-linux-x64.zip" ]; then
          echo "LICENSE-linux-x64.zip exists"
          exit 1
        fi
        if [ -f "LICENSE-linux-arm64.zip" ]; then
          echo "LICENSE-linux-arm64.zip exists"
          exit 1
        fi
        if [ -f "LICENSE-linux-riscv64.zip" ]; then
          echo "LICENSE-linux-riscv64.zip exists"
          exit 1
        fi
        if [ -f "LICENSE-macos-x64.zip" ]; then
          echo "LICENSE-macos-x64.zip exists"
          exit 1
        fi
        if [ -f "LICENSE-macos-arm64.zip" ]; then
          echo "LICENSE-macos-arm64.zip exists"
          exit 1
        fi
        if [ -f "LICENSE-windows-x64.zip" ]; then
          echo "LICENSE-windows-x64.zip exists"
          exit 1
        fi
      shell: bash
    - uses: prantlf/delete-cache-action@v3
      with:
        key: README-linux-x64.zip-${{ github.sha }}
    - uses: prantlf/delete-cache-action@v3
      with:
        key: README-macos-x64.zip-${{ github.sha }}
    - uses: prantlf/publish-release-action@v1
      if: ${{ github.ref_name == 'master' }}
      with:
        no-bump: true
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
