name: Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Simulate test archive
      shell: bash
      run: |
        cp LICENSE LICENSE-linux-x64.zip
        cp README.md README-linux-x64.zip
    - name: Store test archive
      uses: actions/cache/save@v3
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}
        enableCrossOsArchive: true
    - name: Store second test archive
      uses: actions/cache/save@v3
      with:
        path: README-linux-x64.zip
        key: README-linux-x64.zip-${{ github.sha }}
        enableCrossOsArchive: true

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Simulate test archive
      shell: bash
      run: |
        cp LICENSE LICENSE-macos-x64.zip
        cp README.md README-macos-x64.zip
    - name: Store test archive
      uses: actions/cache/save@v3
      with:
        path: LICENSE-macos-x64.zip
        key: LICENSE-macos-x64.zip-${{ github.sha }}
        enableCrossOsArchive: true
    - name: Store second test archive
      uses: actions/cache/save@v3
      with:
        path: README-macos-x64.zip
        key: README-macos-x64.zip-${{ github.sha }}
        enableCrossOsArchive: true

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Simulate test archive
      shell: powershell
      run: Copy-Item "LICENSE" -Destination "LICENSE-windows-x64.zip"
    - name: Store test archive
      uses: actions/cache/save@v3
      with:
        path: LICENSE-windows-x64.zip
        key: LICENSE-windows-x64.zip-${{ github.sha }}
        enableCrossOsArchive: true

  test-and-release:
    needs:
      - linux
      - macos
      - windows
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Test not discarding
      uses: ./
      with:
        discard-shelf: false
    - name: Check archives
      shell: bash
      run: |
        if [ ! -f "LICENSE-linux-x64.zip" ]; then
          echo "LICENSE-linux-x64.zip does not exist"
          exit 1
        fi
        if [ ! -f "LICENSE-macos-x64.zip" ]; then
          echo "LICENSE-macos-x64.zip does not exist"
          exit 1
        fi
        if [ ! -f "LICENSE-windows-x64.zip" ]; then
          echo "LICENSE-windows-x64.zip does not exist"
          exit 1
        fi
    - name: Test custom name
      uses: ./
      with:
        name: README
        include-windows: false
        discard-shelf: false
    - name: Check archives
      shell: bash
      run: |
        if [ ! -f "README-linux-x64.zip" ]; then
          echo "README-linux-x64.zip does not exist"
          exit 1
        fi
        if [ ! -f "README-macos-x64.zip" ]; then
          echo "README-macos-x64.zip does not exist"
          exit 1
        fi
        if [ -f "README-windows-x64.zip" ]; then
          echo "README-windows-x64.zip does not exist"
          exit 1
        fi
    - name: Test discarding
      uses: ./
    - name: Delete archives
      shell: bash
      run: rm LICENSE-linux-x64.zip LICENSE-macos-x64.zip LICENSE-windows-x64.zip README-linux-x64.zip README-macos-x64.zip
    - name: Restore Linux archive
      uses: actions/cache/restore@v3
      with:
        path: LICENSE-linux-x64.zip
        key: LICENSE-linux-x64.zip-${{ github.sha }}
        fail-on-cache-miss: false
        enableCrossOsArchive: true
    - name: Restore macOS archive
      uses: actions/cache/restore@v3
      with:
        path: LICENSE-macos-x64.zip
        key: LICENSE-macos-x64.zip-${{ github.sha }}
        fail-on-cache-miss: false
        enableCrossOsArchive: true
    - name: Restore Windows archive
      uses: actions/cache/restore@v3
      with:
        path: LICENSE-windows-x64.zip
        key: LICENSE-windows-x64.zip-${{ github.sha }}
        fail-on-cache-miss: false
        enableCrossOsArchive: true
    - name: Check archives
      shell: bash
      run: |
        if [ -f "LICENSE-linux-x64.zip" ]; then
          echo "LICENSE-linux-x64.zip exists"
          exit 1
        fi
        if [ -f "LICENSE-macos-x64.zip" ]; then
          echo "LICENSE-macos-x64.zip exists"
          exit 1
        fi
        if [ -f "LICENSE-windows-x64.zip" ]; then
          echo "LICENSE-windows-x64.zip exists"
          exit 1
        fi
    - name: Clear second Linux cache
      uses: prantlf/delete-cache-action@v1
      with:
        key: README-linux-x64.zip-${{ github.sha }}
    - name: Clear second macOS cache
      uses: prantlf/delete-cache-action@v1
      with:
        key: README-macos-x64.zip-${{ github.sha }}
    - name: Publish release
      if: ${{ github.ref_name == 'master' }}
      uses: prantlf/publish-release-action@v1
      with:
        no-bump: true
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
